# This is a basic workflow to help you get started with Actions

name: Functionality Flow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "function"
  encode:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Extract FFmpeg
        run: |
          Expand-Archive .\.github\workflows\test\ffmpeg-essential.zip -DestinationPath .\.github\workflows\test\
          ls .\.github\workflows\test\

      # Runs a set of commands using the runners shell
      - name: Test Multi-Line Echo
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Running `batch encoder.bat`
        run: |
          ls .\.github\workflows\test\
          Invoke-Command -ScriptBlock {& ".\batch encoder.bat" --silent --update false --ffmpegloc .github\workflows\test\ffmpeg.exe}
          
      # - name: Test failure
      #   run: cmd /c "exit /b 4"
