# This is a basic workflow to help you get started with Actions

name: functionality

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "function"
  encode:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Extract FFmpeg
        run: |
          Expand-Archive .\.github\workflows\test\ffmpeg-essential.zip -DestinationPath .\.github\workflows\test\
          ls .\.github\workflows\test\

      - name: Input file exists
        run: if (!(Test-Path '.\.github\workflows\test\testvideo.mp4' )) { throw "Input file not present" }

      - name: Run `batch encoder.bat`
        run: |
          mv ".\batch encoder.bat" ".\.github\workflows\test\batch encoder.bat"
          cd .\.github\workflows\test\
          ls
          Invoke-Command -ScriptBlock {& ".\batch encoder.bat" --silent --update false --ffmpegloc ffmpeg.exe}
          
      - name: Output file exists
        run: if (!(Test-Path '.\.github\workflows\test\testvideo.ENC.mp4' )) { throw "Output file not present" }

      - name: Input file removed
        run: if (Test-Path '.\.github\workflows\test\testvideo.mp4' ) { throw "Input file still present after encode" }

